### PR TITLE
Initial BlockExt trait

### PR DESCRIPTION
**Pull request by edg-l**
Here is the first pr with some utility methods as discussed in #616 , extending it should be easy, also feel free to refactor it or use another name, folder, etc.

I added it behind a feature, because it requires the ods feature.

### CODE REVIEW

**Comment by raviqqe** [comment]
@edg-l It doesn't have to be in this PR but what do you think of splitting the trait into different dialects? For example,

```rust
pub trait SimpleBlock<'ctx> {
    fn arg(&self, idx: usize) -> Result<Value<'ctx, '_>, Error>;
}

pub trait ArithBlock<'ctx> {
    fn addi(
        &self,
        lhs: Value<'ctx, '_>,
        rhs: Value<'ctx, '_>,
        location: Location<'ctx>,
    ) -> Result<Value<'ctx, '_>, Error>;

    // ...
}

pub trait LlvmBlock<'ctx> {
    fn insert_value(&self, /* ... */) -> Result<Value<'ctx, '_>, Error>;

    // ...
}
```

**Comment by edg-l** [comment]
I would use `ArithBlockExt` as a better name because maybe others can confuse it for a Block but i agree with the idea

**Comment by raviqqe** [comment]
@edg-l do you think actually it's possible to generate these block extensions automatically like the ODS dialects API?

**Comment by edg-l** [comment]
> @edg-l do you think actually it's possible to generate these block extensions automatically like the ODS dialects API?

Hm probably not since they have some (little) logic in it often

**Comment by raviqqe** [comment]
Thank you for the changes!

**Pull request merged**
